services:
  lidarr:
    image: ghcr.io/hotio/lidarr:pr-plugins
    container_name: lidarr
    restart: ${RESTART_POLICY}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${LIDARR_PORT:-8686}:8686"
    volumes:
      - "${CONFIG_DIR}/lidarr/config:/config"
      - "${DATA_DIR}:/data"
    networks:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 30s
      timeout: 10s
      retries: 5
